server:
  port: 8089

logging:
  config: classpath:log4j2.xml
  level[0]: info
   #level: info //使用springboot 1.5.9的配置，当使用springboot 2.0时会报错
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mydata?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: Wxy123456
  data:
    mongodb:
      database: log
      host: 192.168.146.134
      port: 27017
      username: loguser
      password: loguser

