server:
  port: 8089

spring:
  application:
    name: springbootredis
  redis:
    port: 6379
    jedis:
      pool:
        max-active: 16
        min-idle: 8
    host: 192.168.146.128
    password:
    database: 0
